python compress_tsfci_graph.py  tsfci_window_graphs/nancy_window_graph_tsfci_lag_1.csv 1
python compress_tsfci_graph.py  tsfci_window_graphs/nancy_window_graph_tsfci_lag_2.csv 2
python compress_tsfci_graph.py  tsfci_window_graphs/nancy_window_graph_tsfci_lag_3.csv 3
python compress_tsfci_graph.py  tsfci_window_graphs/nancy_window_graph_tsfci_lag_4.csv 4
python compress_tsfci_graph.py  tsfci_window_graphs/nancy_window_graph_tsfci_lag_5.csv 5
python compress_tsfci_graph.py  tsfci_window_graphs/nancy_window_graph_tsfci_lag_6.csv 6