# python backtest.py data/Cleaned_S_P_500_Data.csv predictions/sp500_predictions_varlingam_lag_1.csv 1 sp500 varlingam 4
# python backtest.py data/Cleaned_S_P_500_Data.csv predictions/sp500_predictions_varlingam_lag_2.csv 2 sp500 varlingam 4
# python backtest.py data/Cleaned_S_P_500_Data.csv predictions/sp500_predictions_varlingam_lag_3.csv 3 sp500 varlingam 4
# python backtest.py data/Cleaned_CSI_300_Data.csv predictions/csi300_predictions_varlingam_lag_1.csv 1 csi300 varlingam 4
# python backtest.py data/Cleaned_CSI_300_Data.csv predictions/csi300_predictions_varlingam_lag_2.csv 2 csi300 varlingam 4
# python backtest.py data/Cleaned_CSI_300_Data.csv predictions/csi300_predictions_varlingam_lag_3.csv 3 csi300 varlingam 4
# python backtest.py data/Cleaned_CSI_300_Data.csv predictions/csi300_predictions_varlingam_lag_4.csv 4 csi300 varlingam 4
# python backtest.py data/Cleaned_CSI_300_Data.csv predictions/csi300_predictions_varlingam_lag_5.csv 5 csi300 varlingam 4
# python backtest.py data/Cleaned_CSI_300_Data.csv predictions/csi300_predictions_varlingam_lag_6.csv 6 csi300 varlingam 4
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_tsfci_lag_1.csv 1 nancy tsfci 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_tsfci_lag_2.csv 2 nancy tsfci 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_tsfci_lag_3.csv 3 nancy tsfci 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_tsfci_lag_4.csv 4 nancy tsfci 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_tsfci_lag_5.csv 5 nancy tsfci 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_tsfci_lag_6.csv 6 nancy tsfci 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_timino_lag_1.csv 1 nancy timino 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_timino_lag_2.csv 2 nancy timino 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_timino_lag_3.csv 3 nancy timino 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_timino_lag_4.csv 4 nancy timino 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_timino_lag_5.csv 5 nancy timino 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_timino_lag_6.csv 6 nancy timino 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_varlingam_lag_1.csv 1 nancy varlingam 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_varlingam_lag_2.csv 2 nancy varlingam 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_varlingam_lag_3.csv 3 nancy varlingam 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_varlingam_lag_4.csv 4 nancy varlingam 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_varlingam_lag_5.csv 5 nancy varlingam 3
# python backtest.py data/Cleaned_nancy_data.csv predictions/nancy_predictions_varlingam_lag_6.csv 6 nancy varlingam 3
# python backtest.py data/Cleaned_SP500_Data_latest.csv predictions/latest_sp500_predictions_varlingam_lag_1.csv 1 latest_sp500 varlingam 1
# python backtest.py data/Cleaned_SP500_Data_latest.csv predictions/latest_sp500_predictions_varlingam_lag_2.csv 2 latest_sp500 varlingam 4
# python backtest.py data/Cleaned_SP500_Data_latest.csv predictions/latest_sp500_predictions_varlingam_lag_3.csv 3 latest_sp500 varlingam 4
# python backtest.py data/Cleaned_SP500_Data_latest_return.csv predictions/latest_sp500_return_predictions_varlingam_lag_1.csv 1 latest_sp500_return varlingam 4
# python backtest.py data/Cleaned_SP500_Data_latest_return.csv predictions/latest_sp500_return_predictions_varlingam_lag_2.csv 2 latest_sp500_return varlingam 4
# python backtest.py data/Cleaned_SP500_Data_latest_return.csv predictions/latest_sp500_return_predictions_varlingam_lag_3.csv 3 latest_sp500_return varlingam 4
python backtest.py data/Cleaned_SP500_Data_latest_return.csv predictions/latest_sp500_return_predictions_pcmci_lag_1.csv 1 latest_sp500_return pcmci 4 return
python backtest.py data/Cleaned_SP500_Data_latest_return.csv predictions/latest_sp500_return_predictions_pcmci_lag_2.csv 2 latest_sp500_return pcmci 4 return
python backtest.py data/Cleaned_SP500_Data_latest_return.csv predictions/latest_sp500_return_predictions_pcmci_lag_3.csv 3 latest_sp500_return pcmci 4 return