python causal_discovery_varlingam.py data/pelosi-80.csv 1 nancy varlingam
python causal_discovery_varlingam.py data/pelosi-80.csv 2 nancy varlingam
python causal_discovery_varlingam.py data/pelosi-80.csv 3 nancy varlingam
python causal_discovery_varlingam.py data/pelosi-80.csv 4 nancy varlingam
python causal_discovery_varlingam.py data/pelosi-80.csv 5 nancy varlingam
python causal_discovery_varlingam.py data/pelosi-80.csv 6 nancy varlingam
python causal_discovery_varlingam.py data/sp500-80.csv 1 sp500 varlingam
python causal_discovery_varlingam.py data/sp500-80.csv 2 sp500 varlingam
python causal_discovery_varlingam.py data/sp500-80.csv 3 sp500 varlingam
python causal_discovery_varlingam.py data/csi-300-80.csv 1 csi300 varlingam
python causal_discovery_varlingam.py data/csi-300-80.csv 2 csi300 varlingam
python causal_discovery_varlingam.py data/csi-300-80.csv 3 csi300 varlingam
python causal_discovery_varlingam.py data/csi-300-80.csv 4 csi300 varlingam
python causal_discovery_varlingam.py data/csi-300-80.csv 5 csi300 varlingam
python causal_discovery_varlingam.py data/csi-300-80.csv 6 csi300 varlingam
